export const researchConfig = {
  llmApiUrl: process.env.LLM_API_URL ?? process.env.DEEPSEEK_API_URL ?? '',
  llmApiKey: process.env.LLM_API_KEY ?? process.env.DEEPSEEK_API_KEY ?? '',
  llmModel: process.env.LLM_MODEL ?? process.env.DEEPSEEK_MODEL ?? 'deepseek-chat',
voyageApiKey: process.env.VOYAGE_API_KEY ?? '',
  embeddingModel: process.env.EMBEDDING_MODEL ?? 'voyage-3',
  embeddingDimension: parseInt(process.env.EMBEDDING_DIMENSION ?? '1024'),
  vectorSearchLimit: 10,
  vectorSearchThreshold: 0.7,
  maxChunkTokens: 500,
  chunkOverlapTokens: 50,
  papakiloEnabled: process.env.PAPAKILO_SEARCH_ENABLED === 'true',
  papakiloMaxTerms: parseInt(process.env.PAPAKILO_MAX_TERMS ?? '3'),
  papakiloTimeoutMs: parseInt(process.env.PAPAKILO_TIMEOUT_MS ?? '30000'),
  ctahrEnabled: process.env.CTAHR_SEARCH_ENABLED !== 'false',
  ctahrMaxTerms: parseInt(process.env.CTAHR_MAX_TERMS ?? '3'),
  ctahrMaxResultsPerTerm: parseInt(process.env.CTAHR_MAX_RESULTS_PER_TERM ?? '5'),
};
